import type { Product } from "./types";
import { getFallbackImage } from "./product-images";

function p(
  data: Omit<Product, "searchQuery"> & { searchQuery?: string }
): Product {
  const searchQuery = data.searchQuery ?? data.name;
  const image =
    data.image.startsWith("http") ? data.image : getFallbackImage(data.id) ?? data.image;
  return { ...data, searchQuery, image };
}

export const products: Product[] = [
  p({
    id: "shimano-stradic-4000",
    slug: "shimano-stradic-fm-4000",
    name: "Shimano Stradic FM 4000",
    brand: "Shimano",
    categoryId: "kolowrotki",
    image: "https://image.ceneostatic.pl/data/products/169159376/i-shimano-kolowrotek-wedkarski-stradic-fm-4000-st4000fm.jpg",
    searchQuery: "Shimano Stradic FM 4000 ST4000FM",
    description: "Kołowrotek spinningowy z technologią Hagane i X-Ship.",
  }),
  p({
    id: "daiwa-bg-mq-5000",
    slug: "daiwa-bg-mq-5000",
    name: "Daiwa BG MQ 5000",
    brand: "Daiwa",
    categoryId: "kolowrotki",
    image: "",
    searchQuery: "Daiwa BG MQ 5000",
    description: "Wytrzymały kołowrotek morski i spinningowy z aluminiową korpusem.",
  }),
  p({
    id: "fox-horizon-x5",
    slug: "fox-horizon-x5-12ft",
    name: "Fox Horizon X5 12ft 3.5lb",
    brand: "Fox",
    categoryId: "wedki-karp",
    image: "",
    searchQuery: "Fox Horizon X5 12ft 3.5lb",
    description: "Wędka karpiowa o długości 3,66 m i sile rzutu 3,5 lb.",
  }),
  p({
    id: "savage-gear-4d",
    slug: "savage-gear-4d-perch-shad",
    name: "Savage Gear 4D Perch Shad 12.5cm",
    brand: "Savage Gear",
    categoryId: "przynety-sztuczne",
    image: "",
    searchQuery: "Savage Gear 4D Perch Shad 12.5cm",
    description: "Realistyczna przynęta gumowa na okonia i szczupaka.",
  }),
  p({
    id: "rapala-x-rap",
    slug: "rapala-x-rap-10",
    name: "Rapala X-Rap 10",
    brand: "Rapala",
    categoryId: "przynety-sztuczne",
    image: "",
    searchQuery: "Rapala X-Rap 10",
    description: "Klasyczny wobbler do spinningu na szczupaka i sandacza.",
  }),
  p({
    id: "shimano-feeder-12",
    slug: "shimano-aero-x1-feeder-12ft",
    name: "Shimano Aero X1 Feeder 12ft",
    brand: "Shimano",
    categoryId: "wedki-feeder",
    image: "",
    searchQuery: "Shimano Aero X1 Feeder 12ft",
    description: "Wędka feederowa do łowienia z koszyczkiem.",
  }),
  p({
    id: "preston-innovation-4000",
    slug: "preston-innovations-4000",
    name: "Preston Innovations Inception 4000",
    brand: "Preston",
    categoryId: "kolowrotki",
    image: "",
    searchQuery: "Preston Innovations Inception 4000",
    description: "Kołowrotek feeder/spławik w świetnej cenie.",
  }),
  p({
    id: "dragon-express-27",
    slug: "dragon-express-27m",
    name: "Dragon Express 2.7m",
    brand: "Dragon",
    categoryId: "wedki-spinning",
    image: "",
    searchQuery: "Dragon Express 2.7m",
    description: "Wędka spinningowa 2,7 m, ciężar wyrzutu 3–14 g.",
  }),
  p({
    id: "power-pro-300",
    slug: "power-pro-spectra-300m",
    name: "Power Pro Spectra 0.19mm 300m",
    brand: "Power Pro",
    categoryId: "zylki",
    image: "",
    searchQuery: "Power Pro Spectra 0.19mm 300m",
    description: "Plecionka o wysokiej wytrzymałości i cienkim profilu.",
  }),
  p({
    id: "matrix-feeder-set",
    slug: "matrix-feeder-starter-set",
    name: "Matrix Feeder Starter Set",
    brand: "Matrix",
    categoryId: "zestawy",
    image: "",
    searchQuery: "Matrix Feeder Starter Set",
    description: "Zestaw startowy do wędkarstwa feeder.",
  }),
  p({
    id: "delphin-seat",
    slug: "delphin-yogeen-c2g",
    name: "Delphin Yogeen C2G fotel wędkarski",
    brand: "Delphin",
    categoryId: "karp-akcesoria",
    image: "",
    searchQuery: "Delphin Yogeen C2G",
    description: "Wygodny fotel karpiowy z regulacją.",
  }),
  p({
    id: "garmin-echomap",
    slug: "garmin-echomap-uhd-73sv",
    name: "Garmin ECHOMAP UHD 73sv",
    brand: "Garmin",
    categoryId: "elektronika",
    image: "",
    searchQuery: "Garmin ECHOMAP UHD 73sv",
    description: "Echosonda z GPS i mapą ClearVü.",
  }),
  p({
    id: "trabucco-bolo",
    slug: "trabucco-prestige-bolo-600",
    name: "Trabucco Prestige Bolo Master 600",
    brand: "Trabucco",
    categoryId: "wedki-spławik",
    image: "",
    searchQuery: "Trabucco Prestige Bolo Master 600",
    description: "Wędka bolo do spławika na duże dystanse.",
  }),
  p({
    id: "mikado-method",
    slug: "mikado-method-feeder-110",
    name: "Mikado Method Feeder 110cm",
    brand: "Mikado",
    categoryId: "feeder",
    image: "",
    searchQuery: "Mikado Method Feeder 110",
    description: "Mata method feeder do zestawów gruntowych.",
  }),
  p({
    id: "konger-twister",
    slug: "konger-big-tail-twist-6",
    name: "Konger Big Tail Twist 6cm",
    brand: "Konger",
    categoryId: "przynety-sztuczne",
    image: "",
    searchQuery: "Konger Big Tail Twist 6cm",
    description: "Guma spinningowa — bestseller w Polsce.",
  }),
  p({
    id: "dam-combo",
    slug: "dam-fire-wave-xp-combo",
    name: "DAM Fire Wave XP Spinning Combo 2.44m",
    brand: "DAM",
    categoryId: "zestawy",
    image: "",
    searchQuery: "DAM Fire Wave XP Spinning Combo",
    description: "Zestaw wędka + kołowrotek 3000 z plecionką.",
  }),
  p({
    id: "sensas-zaneta",
    slug: "sensas-zaneta-3000",
    name: "Sensas Zanęta River 3000",
    brand: "Sensas",
    categoryId: "zanety",
    image: "",
    searchQuery: "Sensas Zanęta River 3000",
    description: "Zanęta do rzeki i kanałów — 3 kg.",
  }),
  p({
    id: "fox-bite-alarm",
    slug: "fox-micron-mx-bite-alarm",
    name: "Fox Micron MX Bite Alarm Set",
    brand: "Fox",
    categoryId: "karp-akcesoria",
    image: "",
    searchQuery: "Fox Micron MX Bite Alarm",
    description: "Zestaw sygnalizatorów karpiowych z odbiornikiem.",
  }),
  p({
    id: "penn-pursuit",
    slug: "penn-pursuit-v-combo",
    name: "Penn Pursuit V Inshore Combo 2.44m",
    brand: "Penn",
    categoryId: "zestawy",
    image: "",
    searchQuery: "Penn Pursuit V Inshore Combo",
    description: "Zestaw morski/spinningowy Penn Pursuit V.",
  }),
  p({
    id: "humminbird",
    slug: "humminbird-helix-5-chirp",
    name: "Humminbird Helix 5 CHIRP GPS G3",
    brand: "Humminbird",
    categoryId: "elektronika",
    image: "",
    searchQuery: "Humminbird Helix 5 CHIRP GPS G3",
    description: "Echosonda z CHIRP i mapą kartograficzną.",
  }),
  p({
    id: "shimano-technium",
    slug: "shimano-technium-float-04",
    name: "Shimano Technium Float 0.4mm 300m",
    brand: "Shimano",
    categoryId: "zylki",
    image: "",
    searchQuery: "Shimano Technium Float 0.4mm 300m",
    description: "Żyłka monofilamentowa do spławika.",
  }),
  p({
    id: "gamakatsu-hooks",
    slug: "gamakatsu-karp-haczyki-10",
    name: "Gamakatsu Karp Haczyki #10 (10 szt.)",
    brand: "Gamakatsu",
    categoryId: "haczyki",
    image: "",
    searchQuery: "Gamakatsu Karp Haczyki 10",
    description: "Haczyki karpiowe wysokiej jakości.",
  }),
  p({
    id: "traper-chair",
    slug: "traper-feeder-gst-pro",
    name: "Traper Feeder GST Pro Red",
    brand: "Traper",
    categoryId: "karp-akcesoria",
    image: "",
    searchQuery: "Traper Feeder GST Pro",
    description: "Fotel feeder z oparciem i podłokietnikami.",
  }),
  p({
    id: "minn-kota",
    slug: "minn-kota-endura-55",
    name: "Minn Kota Endura C2 55",
    brand: "Minn Kota",
    categoryId: "lodz-silniki",
    image: "",
    searchQuery: "Minn Kota Endura C2 55",
    description: "Silnik elektryczny do pontonu — 12V 55 lb.",
  }),
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.categoryId === categoryId);
}
